version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: finalproject-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: finalproject-backend
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=omrans_fruits_db
      - CORS_ORIGINS=*
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=/api
    container_name: finalproject-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:


